TEST_DNS: www.google.com
DNS_UPSTREAM: 8.8.4.4
DNS_DOMAIN: example.com
DNS_SEARCH: example.com
HOSTNAME: fuel
ADMIN_NETWORK:
  interface: vboxnet0
  cidr: 10.20.0.0/24
  netmask: 255.255.255.0
  size: 256
  static_start: 10.20.0.2
  static_end: 10.20.0.127
  first: 10.20.0.128
  last: 10.20.0.254
